### ISSUE TITLE
Errores después de update master

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/UrboCore-www#112]
- [x] Los mapas pequeños de estado general no funcionan en casi ningún vertical:
![image](https://user-images.githubusercontent.com/13120924/38367185-4bd70f78-38e2-11e8-8529-72f783a00390.png)
![image](https://user-images.githubusercontent.com/13120924/38367279-8988127c-38e2-11e8-9035-4d638b955fc4.png)
![image](https://user-images.githubusercontent.com/13120924/38367363-be0e9da4-38e2-11e8-85ec-c739d6558254.png)

- [x] Widget de cantidad por calendario/hora se queda cargando:
![image](https://user-images.githubusercontent.com/13120924/38367481-20a16b22-38e3-11e8-9ba8-528a7af9268e.png)

- [ ] En Málaga Lab - Residuos parece que no hay nada (puede que pasase antes y el de distrito telefónica va bien)

- [x] Hay que traducir los textos de "Añadir frame" e "Iniciar sesión con IDM"

**Comment by Josmorsot** [comment]
@ignaciodomingo MalagaLab parece que no tiene ningun problema

**Comment by ignaciodomingo** [comment]
![image](https://user-images.githubusercontent.com/13120924/38377336-fb9cfa54-38fa-11e8-9bbb-02b9ba50fd8d.png)
No se ha traducido eso. ¿Por la tilde quizás?
